version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=AnimeDb;User Id=sa;Password=MinhaSenha123!;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MinhaSenha123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
